{
  imports = [
    ./bat.nix
    ./bottom.nix
    ./cli.nix
    ./foot.nix
    #./gpg.nix
    ./git.nix
    ./inlyne.nix
    ./neofetch.nix
    ./nix.nix
    ./screenshot-area.nix
    ./screenshot-full.nix
    ./skim.nix
    ./transient-services.nix
    ./yazi
    ./xdg.nix
    ./zoxide.nix
    ./zsh.nix
  ];
}
